// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO7xS5KeHo39XiIxe93iYwiw67D-2FJOc',
    appId: '1:749779324985:web:3fdc975e9d553fa31fbde8',
    messagingSenderId: '749779324985',
    projectId: 'msgprogram-d0c15',
    authDomain: 'msgprogram-d0c15.firebaseapp.com',
    storageBucket: 'msgprogram-d0c15.appspot.com',
    measurementId: 'G-00SQNF9BQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1zhgX74Jn9PDzxUWt1sZgOCPXMscvx-A',
    appId: '1:749779324985:android:93532c9fa6125fbc1fbde8',
    messagingSenderId: '749779324985',
    projectId: 'msgprogram-d0c15',
    storageBucket: 'msgprogram-d0c15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJxE2EtEYUgnuswzh5RlBuSujHEJozcU',
    appId: '1:749779324985:ios:73cc49599ac6c9141fbde8',
    messagingSenderId: '749779324985',
    projectId: 'msgprogram-d0c15',
    storageBucket: 'msgprogram-d0c15.appspot.com',
    iosBundleId: 'com.example.kakaoProgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJxE2EtEYUgnuswzh5RlBuSujHEJozcU',
    appId: '1:749779324985:ios:73cc49599ac6c9141fbde8',
    messagingSenderId: '749779324985',
    projectId: 'msgprogram-d0c15',
    storageBucket: 'msgprogram-d0c15.appspot.com',
    iosBundleId: 'com.example.kakaoProgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO7xS5KeHo39XiIxe93iYwiw67D-2FJOc',
    appId: '1:749779324985:web:36c3a67770855f891fbde8',
    messagingSenderId: '749779324985',
    projectId: 'msgprogram-d0c15',
    authDomain: 'msgprogram-d0c15.firebaseapp.com',
    storageBucket: 'msgprogram-d0c15.appspot.com',
    measurementId: 'G-LTD6WNM165',
  );
}
